### PR TITLE
fix serialized_existing_memories dump field bug

### PR DESCRIPTION
**Pull request by boss-mao**
Fixes # (issue)
fix serialized_existing_memories dump field bug

### CODE REVIEW

**Comment by lemon-little** [comment]
Fixes #1648  #1645

**Review by lemon-little — APPROVED** [review]

**Comment by Dev-Khant** [comment]
Hey @boss-mao Can you please sign the CLA?

**Comment by boss-mao** [comment]
> Hey @boss-mao Can you please sign the CLA?

I have already signed CLA

**Comment by boss-mao** [comment]
> Hey @boss-mao Can you please sign the CLA?

sign the CLA

**Comment by Dev-Khant** [comment]
@boss-mao Thanks for your contribution.

**Pull request merged**
