### PR TITLE
Vectara integration

### PR DESCRIPTION
**Pull request by ofermend**
## Description

This provides an integration with Vectara as a vector DB as well as RAG platform.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update

## How Has This Been Tested?

- [X] Unit Test

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ofermend** [comment]
Hey EmbedChain folks - just checking if you have any feedback about the PR

**Comment by ofermend** [comment]
Hey @deshraj - I wanted to check again whether you can take a look at the PR to see if it works? I just updated it to remove any conflicts so it's up to date with the latest main branch.

**Comment by ofermend** [comment]
Checking if this can be reviewed please?
@taranjeet 

Thank you
Ofer

**Comment by ofermend** [comment]
Hi there - please let me know if this PR can be reviewed?

**Comment by taranjeet** [comment]
Hey @ofermend thanks for your contribution. We are prioritizing integrations based on user feedback, so closing this for now. Will re-open if there are several user asking for this integration.

**Pull request closed without merging**
