### PR TITLE
AzureOpenAI Embedding Model and LLM Model Initialisation from Config. 

### PR DESCRIPTION
**Pull request by ketangangal**
## Description

AzureOpenAI Configuration for Mem0.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

# Changes 

**1. Memory config** 
```
  config = {
      "llm": {
          "provider": "azure_openai",
          "config": {
              "model" : "gpt-4o",
              "temperature": 0.1,
              "max_tokens": 2000,
              "azure_kwargs" : {
                  "azure_deployment" : "",
                  "api_version" : "",
                  "azure_endpoint" : "",
                  "api_key" : ""
              }
          }
      },
      "vector_store": {
          "provider": "qdrant",
          "config": {
              "collection_name": "",
              "embedding_model_dims": 1536,
              "url": "",
              "api_key": "",
          }
      },
      "embedder": {
          "provider": "azure_openai",
          "config": {
              "model": "text-embedding-3-small",
              "azure_kwargs" : {
                  "api_version" : "",
                  "azure_deployment" : "",
                  "azure_endpoint" : "",
                  "api_key": ""
              }

          }
      }
  }
    
    m = Memory.from_config(config_dict=config)
```

**2. Seperate Env Variables** 

Need if both model are initialise together then API keys will conflict hence the change. 

AzureOpenAI for LLM
```
LLM_AZURE_OPENAI_API_KEY
LLM_AZURE_DEPLOYMENT
LLM_AZURE_ENDPOINT
LLM_AZURE_API_VERSION
```

AzureOpenAI for Embeddings
```
EMBEDDING_AZURE_OPENAI_API_KEY
EMBEDDING_AZURE_DEPLOYMENT
EMBEDDING_AZURE_ENDPOINT
EMBEDDING_AZURE_API_VERSION
```

FYI @prateekchhikara @taranjeet @deshraj @Dev-Khant

### CODE REVIEW

**Comment by Dev-Khant** [comment]
Hey @ketangangal Can you please resolve the merge conflicts so we can run the tests?

**Comment by ketangangal** [comment]
Hey @Dev-Khant sure!

**Comment by Dev-Khant** [comment]
@ketangangal Can you please check failing tests?

**Comment by ketangangal** [comment]
> @ketangangal Can you please check failing tests?

done

**Comment by ketangangal** [comment]
FYI @deshraj @Dev-Khant can you review and let me know if changes are required.

**Review by Dev-Khant — COMMENTED** [review]
Hey @ketangangal Can you please update the docs as well where we have used `AZURE_OPENAI_API_KEY` and other keys?

Also the checks are still failing, please run and check if the tests are passing locally.

**Review by Dev-Khant — APPROVED** [review]

**Comment by Dev-Khant** [comment]
@ketangangal Thanks for the contribution.

**Pull request merged**
