### PR TITLE
feat(memory): keep memory language

### LINKED ISSUE #1817: Save fact data in db with same language with user's input
### 🚀 The feature

When we add a memory in some languages other than English, Chinese for example, the deduced fact can keep the deduced fact's language same with user input.

### Motivation, pitch

The motivation is that we don't want the memory be translate from Chinese(user input) to English(the deduced fact with the default prompt) and then translate back to Chinese when answer according memory.

### PR DESCRIPTION
**Pull request by shenxiangzhuang**
## Description

- Memory Save(deduced fact): Keep the memory's language same with input

Fixes #1817 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Dev-Khant** [comment]
Hey @shenxiangzhuang Can you please provide 1-2 test scripts for testing it?

**Comment by shenxiangzhuang** [comment]
> Can you please provide 1-2 test scripts for testing it?

Sure. The testing code is pretty simple:
```python
from mem0 import Memory

# define _MEM0_CONFIG here: llm: openai, embedding: ollama, vector_store: qdrant

def main():
    m = Memory.from_config(_MEM0_CONFIG)
    result = m.add("喜欢周末玩乒乓球", user_id="张三", metadata={"category": "hobbies"})
    print(f"result: {result}")
    related_memories = m.search(query="张三的爱好是什么", user_id="张三")
    print(f"related_memories: {related_memories}")


if __name__ == '__main__':
    main()

```

Before the change of prompt, we got output:
```
related_memories: [{'id': '76102c6b-05d2-4a05-b843-a2e11ea2f0a0', 'memory': 'Likes playing table tennis on weekends', 'hash': 'ac3cd5287d0a2dee848ee3b12c31703e', 'metadata': {'category': 'hobbies'}, 'score': 0.36019355, 'created_at': '2024-09-05T03:32:58.195462-07:00', 'updated_at': '2024-09-05T03:33:33.279893-07:00', 'user_id': '张三'}]
```
We can see the `memory` is `Likes playing table tennis on weekends`.

After the change of prompt, we got output:
```
related_memories: [{'id': '76102c6b-05d2-4a05-b843-a2e11ea2f0a0', 'memory': '喜欢周末玩乒乓球', 'hash': 'ac3cd5287d0a2dee848ee3b12c317etadata': {'category': 'hobbies'}, 'score': 0.6970718, 'created_at': '2024-09-05T03:32:58.195462-07:00', 'updated_at': None, 'user_id': '张三'}]
```
We can see the `memory` is `喜欢周末玩乒乓球`. It's in Chinese now, with the same language of memory input.

**Review by Dev-Khant — APPROVED** [review]

**Comment by Dev-Khant** [comment]
Thanks @shenxiangzhuang I tested for multiple languages, and it works well.

**Comment by Fluchw** [comment]
Still unable to maintain language consistency well, he always saves my Chinese as English

**Pull request merged**
