### PR TITLE
Add vector store integration of OceanBase for EmbedChain

### PR DESCRIPTION
**Pull request by GITHUBear**
## Description

[OceanBase Database](https://github.com/oceanbase/oceanbase) is a distributed relational database.
It is developed entirely by Ant Group. The OceanBase Database is built on a common server cluster.
Based on the Paxos protocol and its distributed structure, the OceanBase Database provides high availability and linear scalability.

OceanBase currently has the ability to store vectors. Here we introduce OceanBase as an alternative vector store.

You can deploy a standalone OceanBase server by following steps:

1. Start a docker container via the following command:
```shell
docker run --name=ob433 -e MODE=slim -p 2881:2881 -d oceanbase/oceanbase-ce:4.3.3.0-100000142024101215
```

2. Donwload the partner package:
```shell
pip install --upgrade --quiet pyobvector
```

3. Check the connection to OceanBase and set the memory usage ratio for vector data:
```python
from pyobvector import ObVecClient

tmp_client = ObVecClient()
tmp_client.perform_raw_text_sql(
    "ALTER SYSTEM ob_vector_memory_limit_percentage = 30"
)
```

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

unittest in `embedchain/tests/vectordb/test_oceanbase.py`

Please delete options that are not relevant.

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by GITHUBear** [comment]
Hi @Dev-Khant , could you please review my PR? Any feedback will be valuable. Thank you!

**Comment by HanMxSJ** [comment]
Oceanbase is an important database of Alibaba Group, and OB's capabilities can help improve the adaptation of embedchain. The relevant code is very important to me, I need this feature, can you merge it ASAP.

**Comment by taranjeet** [comment]
Hey @GITHUBear 
Thank you for your contribution! At the moment, we’re focusing on integrations that are highly requested by the community. We appreciate your effort and will keep this in mind for future priorities.

**Comment by GITHUBear** [comment]
@taranjeet Thank you for your reply! We are looking forward to future contributions, please remind us when it's ready for integration with OceanBase.

**Pull request closed without merging**
