### PR TITLE
Fixes for LLM providers LiteLLM and TogetherAI

### PR DESCRIPTION
**Pull request by Ataraksia**
## Description

Added LiteLLM and TogetherAI to the LLM provider validator list so they wouldn't error out as unsupported, and then additionally renamed TogetherAI so it better match both the name of the LLM as well as fit the example in the docs.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by rshah713 — APPROVED** [review]
Any news on this? LGTM

**Comment by Ataraksia** [comment]
Saw the PR you referenced had some changes I failed to include, specifically another provider, and a change to the container type.  I also felt it made sense to sort it given the increased length.

**Comment by Dev-Khant** [comment]
Hey @Ataraksia Thank you for working on this and for pointing out the doc issue. But here we would keep `together` as it's the standard name we use across Mem0 and Embedchain.

Therefore, closing this issue. Please feel free to work on other issues and let us know if you need any help.

**Comment by thedunston** [comment]
When I tried to use togetherai using the example code. I get:

  Value error, Unsupported LLM provider: togetherai [type=value_error, input_value={'model': 'deepseek-ai/De...0.2, 'max_tokens': 1500}, input_type=dict]
  
  Ii if i change to "together" i get:
  openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
  
 using the example
 ```
  import os
from mem0 import Memory

os.environ["TOGETHER_API_KEY"] = "your-api-key"

config = {
    "llm": {
        "provider": "togetherai",
        "config": {
            "model": "mistralai/Mixtral-8x7B-Instruct-v0.1",
            "temperature": 0.2,
            "max_tokens": 1500,
        }
    }
}

m = Memory.from_config(config)
m.add("Likes to play cricket on weekends", user_id="alice", metadata={"category": "hobbies"})
```

```os.environ["TOGETHER_API_KEY"] = "your-api-key"```

and tried just setting the ```TOGETER_API_KEY="xxxxx"``` on the cli and no change.

https://docs.mem0.ai/llms#togetherai

mem0ai version: 0.1.67  using Python 3.11.

**Pull request closed without merging**
