### PR TITLE
bug fix, need add base_url for ollama

### PR DESCRIPTION
**Pull request by forrestzhang**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

### CODE REVIEW

**Comment by forrestzhang** [comment]
fix

ValidationError: 1 validation error for Ollama
base_url
  none is not an allowed value (type=type_error.none.not_allowed)
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?ec154dfb-debf-4efe-9e18-7fb83b55f265) or open in a [text editor](command:workbench.action.openLargeOutput?ec154dfb-debf-4efe-9e18-7fb83b55f265). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by forrestzhang** [comment]
add base_url to fix:


---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[6], [line 1](vscode-notebook-cell:?execution_count=6&line=1)
----> [1](vscode-notebook-cell:?execution_count=6&line=1) answer = app.query("who is elon musk?")

File ~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:533, in EmbedChain.query(self, input_query, config, dry_run, where, citations, **kwargs)
    [529](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:529)         answer, token_info = self.llm.query(
    [530](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:530)             input_query=input_query, contexts=contexts_data_for_llm_query, config=config, dry_run=dry_run
    [531](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:531)         )
    [532](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:532)     else:
--> [533](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:533)         answer = self.llm.query(
    [534](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:534)             input_query=input_query, contexts=contexts_data_for_llm_query, config=config, dry_run=dry_run
    [535](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:535)         )
    [537](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:537) # Send anonymous telemetry
    [538](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/embedchain.py:538) self.telemetry.capture(event_name="query", properties=self._telemetry_props)

File ~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:251, in BaseLlm.query(self, input_query, contexts, config, dry_run, memories)
    [249](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:249)     answer, token_info = self.get_answer_from_llm(prompt)
    [250](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:250) else:
--> [251](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:251)     answer = self.get_answer_from_llm(prompt)
    [252](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:252) if isinstance(answer, str):
    [253](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:253)     logger.info(f"Answer: {answer}")

File ~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:167, in BaseLlm.get_answer_from_llm(self, prompt)
    [157](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/embedchain/llm/base.py:157) def get_answer_from_llm(self, prompt: str):
...
    [343](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/forrest/PlayGround/mem0/~/miniconda3/envs/llamaindex/lib/python3.11/site-packages/pydantic/v1/main.py:343)     object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for Ollama
base_url
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Dev-Khant** [comment]
@forrestzhang Thanks for finding this issue, can you please sign the CLA?

**Comment by Dev-Khant** [comment]
@forrestzhang Can you please sign the CLA?

**Comment by forrestzhang** [comment]
> @forrestzhang Can you please sign the CLA?

It seems that I have already sign CLA. Could you please help me to check that?

**Comment by forrestzhang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Dev-Khant** [comment]
Hey @forrestzhang You should github [doc](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) to how to setup account for commits.

**Comment by forrestzhang** [comment]
Please close this merge. I will try to push. Thx.

**Pull request closed without merging**
