### PR TITLE
Add Support for Vertex AI Embeddings

### LINKED ISSUE #1827: Add Support for Vertex AI Embeddings
### 🚀 The feature

Integrate **Vertex AI embeddings** models from **Litellm** into **Mem0** as an additional option for users

### Motivation, pitch

Provide users with more choice by including Vertex AI embeddings alongside existing options. Vertex AI offers a pay-as-you-go pricing model for individual developers, unlike OpenAI, which primarily serves organizations. Adding Vertex AI embeddings would provide more flexible and accessible options for developers.

### PR DESCRIPTION
**Pull request by Divyanshu9822**
## Description

Added support for  vertex ai embeddings 

Fixes #1827
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [x] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Divyanshu9822** [comment]
@Dev-Khant Please review and let me know if any changes are needed. Additionally, inform me if the documentation needs to be updated based on these changes

**Review by Dev-Khant — COMMENTED** [review]
This is a good approach, can you please check `vertexai` library and implement this?

**Comment by Dev-Khant** [comment]
Hey @Divyanshu9822 Changes looks good to me. Can you please add this to docs as well?

**Review by Dev-Khant — COMMENTED** [review]
Add changes to docs as well.

**Comment by Divyanshu9822** [comment]
> Hey @Divyanshu9822 Changes looks good to me. Can you please add this to docs as well?

Docs updated, and I've also added the `embedding_dims` parameter to vertexai

**Review by Dev-Khant — APPROVED** [review]

**Comment by Dev-Khant** [comment]
LGTM, @Divyanshu9822 thanks for the contribution.

**Pull request merged**
