### PR TITLE
Azure support

### PR DESCRIPTION
**Pull request by crazyxixi**
## Description

Provided is the access to the azure_openai API, which requires the configuration of llm and embedder in the config. If the API keys for the two are different, they need to be configured separately; otherwise, it is sufficient to configure the environment variables for llm only.

Fixes # (azure_openai support)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

To run the azure_test.py file under the test directory directly, you can do so. However, you must first input the keys for llm and embedder, as well as the endpoint and version.

Please delete options that are not relevant.

- [ ] Unit Test

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Dev-Khant** [comment]
@crazyxixi Can you please resolve the conflicts?

**Comment by crazyxixi** [comment]
> @crazyxixi Can you please resolve the conflicts?

I've submitted new support to accommodate the new version

**Comment by Dev-Khant** [comment]
Hey @crazyxixi Can you please create one PR with all the necessary changes for Azure support?

**Comment by crazyxixi** [comment]
> Hey @crazyxixi Can you please create one PR with all the necessary changes for Azure support?

I have submitted a new pull request called "Azure embedding support."

**Comment by Dev-Khant** [comment]
Closing this PR as changes have already been implemented.

**Pull request closed without merging**
