### PR TITLE
Milvus Integration

### LINKED ISSUE #1617: Add Milvus Integration
### 🚀 The feature

Add a new vector database option as milvus

### Motivation, pitch

The new vector database option provides more possible combinations of usage and can attract more customers

### PR DESCRIPTION
**Pull request by Jacksonxhx**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactor (does not change functionality, e.g. code style improvements, linting)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #1617
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by geeker-smallwhite** [comment]
我需要这个功能，你能尽快合并吗

**Comment by zc277584121** [comment]
need this feature, can someone please help to merge it

**Comment by ketangangal** [comment]
Hello @deshraj @Dev-Khant , 
I am working on this I have already created a branch i will raise pr in  1-2 days.

**Comment by Dev-Khant** [comment]
Hey @Jacksonxhx Are you working on this issue? Please let us know.

**Comment by zc277584121** [comment]
looking forword to @ketangangal  's contributing.  @Jacksonxhx seems have no time to deal with this, and if there are any problem, I can support it.

**Comment by ketangangal** [comment]
@zc277584121 watch out : https://github.com/mem0ai/mem0/pull/1821

**Comment by Dev-Khant** [comment]
Closing this PR has Milvus has been added in #1821.

**Pull request closed without merging**
