### PR TITLE
Fixing the bug when using Huggingface Models

### LINKED ISSUE #1752: Hugging Face Embedding Error with Bug
### 🐛 Describe the bug

my code
```python
import os
from mem0 import Memory

# os.environ["OPENAI_API_KEY"] = "none" # for embedder

config = {
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "gemma2",
            "temperature": 0,
            "max_tokens": 2048,
            "ollama_base_url": "http://localhost:11434",  # Ensure this URL is correct
        },
    },
    "vector_store": {
        "provider": "chroma",
        "config": {
            "collection_name": "test",
            "path": "resource/knbase",
        }
    },
    "embedder": {
        "provider": "huggingface",
        "config": {
            "model": "multi-qa-MiniLM-L6-cos-v1"
        }
    }
}

m = Memory.from_config(config)
m.add("我喜欢在周末骑自行车", user_id="alice", metadata={"category": "hobbies"})
```

bug info
```bash
File [~/miniforge3/lib/python3.12/site-packages/chromadb/api/types.py:508](http://localhost:8888/lab/tree/~/miniforge3/lib/python3.12/site-packages/chromadb/api/types.py#line=507), in validate_embeddings(embeddings)
    504     raise ValueError(
    505         f"Expected embeddings to be a list with at least one item, got {len(embeddings)} embeddings"
    506     )
    507 if not all([isinstance(e, list) for e in embeddings]):
--> 508     raise ValueError(
    509         "Expected each embedding in the embeddings to be a list, got "
    510         f"{list(set([type(e).__name__ for e in embeddings]))}"
    511     )
    512 for i, embedding in enumerate(embeddings):
    513     if len(embedding) == 0:

ValueError: Expected each embedding in the embeddings to be a list, got ['float']
```

### PR DESCRIPTION
**Pull request by parshvadaftari**
## Description

Changing the return type of the HuggingFace Embeddings from ndarray to List

Fixes #1752 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [x] Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #1752 
- [x] Made sure Checks passed

### CODE REVIEW

**Comment by parshvadaftari** [comment]
Weird as it runs on my Macbook. The Tests are successfull with all 3 of the python versions, 3.10, 3.11 and 3.12.
Is it due to Macbook?

**Comment by Dev-Khant** [comment]
Hey @parshvadaftari Can you please check the failing tests?

**Comment by parshvadaftari** [comment]
@Dev-Khant I've attached the test script for the updated huggingface embeddings. And made sure that the test have passed on my locak using the `make test`.

**Review by Dev-Khant — APPROVED** [review]

**Comment by Dev-Khant** [comment]
Thanks for the contribution @parshvadaftari

**Pull request merged**
